// For building the open-source release of TalkBack.

apply plugin: 'com.android.application'

apply from: 'shared.gradle'

dependencies {
    implementation project(':talkback')
}

buildscript {
    ext.kotlin_version = "2.2.21"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Here we set the version of the Android Gradle Plugin used by this
        // script. It is best to use as new a version as possible, but beware
        // that each version of the Gradle Plugin requires that the version of
        // Gradle (used to drive the build) be a certain version or above. The
        // correspondence is tracked here:
        // https://developer.android.com/build/releases/gradle-plugin#updating-gradle
        classpath 'com.android.tools.build:gradle:9.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()

if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    buildToolsVersion '36.1.0'
    namespace = talkbackApplicationId
    defaultConfig {
        applicationId talkbackApplicationId
        versionName "15.1"
        versionCode 21
        minSdk 26
        targetSdk 35
        compileSdk {
            version = release(36) {
                it.minorApiLevel = 1
            }
        }
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
        multiDexEnabled = true
    }
    packagingOptions {
        exclude 'LICENSE'
        exclude 'README'
    }
    lint {
        checkReleaseBuilds = false
        abortOnError = false
    }
    productFlavors {
        phone {
            dimension "target"
        }
    }

    dependenciesInfo {
        includeInApk = false
    }

    packaging {
        resources {
            excludes += [
                "**/MANIFEST.MF",
                "DebugProbesKt.bin",
                "META-INF/**.version",
                "kotlin-tooling-metadata.json",
                "kotlin/**.kotlin_builtins"
            ]
        }
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties["storeFile"])
                storePassword keystoreProperties["storePassword"]
                keyAlias keystoreProperties["keyAlias"]
                keyPassword keystoreProperties["keyPassword"]
                enableV2Signing = true
		                enableV3Signing = true
                enableV4Signing = true
            }
        }
    }

    buildTypes {
        release {
            if (keystorePropertiesFile.exists()) {
                signingConfig = signingConfigs.release
            }
            minifyEnabled = false
            shrinkResources = false
            proguardFiles getDefaultProguardFile(
                "proguard-android-optimize.txt"
            ), "proguard-rules.pro"
        }
    }
}
